version: '3.7'

# Define services

services:
  app-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    restart: always
    depends_on:
      - db
    environment: # Pass environment variables to the service
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/quanlysinhvien
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: password
      networks: # Networks to join (Services on the same network can communicate with each other using their name)
        - backend

# Database Service (Mysql)
mysql-standalone:
  image: mysql:8
  ports:
    -"3306:3306"
  restart: always
  environment:
    MYSQL_DATABASE: quanlysinhvien
    MYSQL_USER: sa
    MYSQL_PASSWORD: password
    MYSQL_ROOT_PASSWORD: password

